# Generated by Django 2.2.3 on 2019-07-26 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=120)),
                ('school_type', models.CharField(choices=[('boys_school', 'Boys School'), ('girls_school', 'Girls School'), ('coeducation_school', 'Codecuation School')], default='coeducation_school', max_length=20)),
                ('principal_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='crud_system.School')),
            ],
        ),
    ]
