# Generated by Django 2.2.3 on 2019-07-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_system', '0002_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
